Shader "Shader Forge/LocalizedShake" {
	Properties {
		_MainTex ("MainTex", 2D) = "white" {}
		_xOffset ("xOffset", Float) = 0
		_yOffset ("yOffset", Float) = 0
		[MaterialToggle] PixelSnap ("Pixel snap", Float) = 0
	}
	SubShader {
		Tags { "CanUseSpriteAtlas" = "true" "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent+1" "RenderType" = "Transparent" }
		GrabPass {
		}
		Pass {
			Name "FORWARD"
			Tags { "CanUseSpriteAtlas" = "true" "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "ForwardBase" "PreviewType" = "Plane" "QUEUE" = "Transparent+1" "RenderType" = "Transparent" "SHADOWSUPPORT" = "true" }
			Blend One OneMinusSrcAlpha, One OneMinusSrcAlpha
			ZClip Off
			ZWrite Off
			Cull Off
			GpuProgramID 46814
			Program "vp" {
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov r1, r0
					    mov o2, r0
					    mov o1.xy, v1
					    mad o0.xy, r1.w, c255, r1
					    mov o0.zw, r1
					
					// approximately 9 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov r1, r0
					    mov o2, r0
					    mov o1.xy, v1
					    mad o0.xy, r1.w, c255, r1
					    mov o0.zw, r1
					
					// approximately 9 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "VERTEXLIGHT_ON" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov r1, r0
					    mov o2, r0
					    mov o1.xy, v1
					    mad o0.xy, r1.w, c255, r1
					    mov o0.zw, r1
					
					// approximately 9 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "VERTEXLIGHT_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "VERTEXLIGHT_ON" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov r1, r0
					    mov o2, r0
					    mov o1.xy, v1
					    mad o0.xy, r1.w, c255, r1
					    mov o0.zw, r1
					
					// approximately 9 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "VERTEXLIGHT_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "PIXELSNAP_ON" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _ScreenParams;
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//   _ScreenParams      c4       1
					//
					
					    vs_3_0
					    def c5, 0.5, 0, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r1.w, c3, v0
					    rcp r0.z, r1.w
					    mul r0.xy, r0.z, r0
					    mov r2.x, c5.x
					    mul r0.zw, r2.x, c4.xyxy
					    mad r0.xy, r0, r0.zwzw, c5.x
					    frc r2.xy, r0
					    add r0.xy, r0, -r2
					    rcp r2.x, r0.z
					    rcp r2.y, r0.w
					    mul r0.xy, r0, r2
					    mul r1.xy, r1.w, r0
					    dp4 r1.z, c2, v0
					    mov r3, r1
					    mov o2, r1
					    mov o1.xy, v1
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 20 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "PIXELSNAP_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					div r1.xy, r0.xyxx, r0.wwww
					mul r1.zw, cb0[6].xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
					mul r1.xy, r1.zwzz, r1.xyxx
					round_ne r1.xy, r1.xyxx
					div r1.xy, r1.xyxx, r1.zwzz
					mul r0.xy, r0.wwww, r1.xyxx
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "PIXELSNAP_ON" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _ScreenParams;
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//   _ScreenParams      c4       1
					//
					
					    vs_3_0
					    def c5, 0.5, 0, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r1.w, c3, v0
					    rcp r0.z, r1.w
					    mul r0.xy, r0.z, r0
					    mov r2.x, c5.x
					    mul r0.zw, r2.x, c4.xyxy
					    mad r0.xy, r0, r0.zwzw, c5.x
					    frc r2.xy, r0
					    add r0.xy, r0, -r2
					    rcp r2.x, r0.z
					    rcp r2.y, r0.w
					    mul r0.xy, r0, r2
					    mul r1.xy, r1.w, r0
					    dp4 r1.z, c2, v0
					    mov r3, r1
					    mov o2, r1
					    mov o1.xy, v1
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 20 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "PIXELSNAP_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					div r1.xy, r0.xyxx, r0.wwww
					mul r1.zw, cb0[6].xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
					mul r1.xy, r1.zwzz, r1.xyxx
					round_ne r1.xy, r1.xyxx
					div r1.xy, r1.xyxx, r1.zwzz
					mul r0.xy, r0.wwww, r1.xyxx
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "VERTEXLIGHT_ON" "PIXELSNAP_ON" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _ScreenParams;
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//   _ScreenParams      c4       1
					//
					
					    vs_3_0
					    def c5, 0.5, 0, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r1.w, c3, v0
					    rcp r0.z, r1.w
					    mul r0.xy, r0.z, r0
					    mov r2.x, c5.x
					    mul r0.zw, r2.x, c4.xyxy
					    mad r0.xy, r0, r0.zwzw, c5.x
					    frc r2.xy, r0
					    add r0.xy, r0, -r2
					    rcp r2.x, r0.z
					    rcp r2.y, r0.w
					    mul r0.xy, r0, r2
					    mul r1.xy, r1.w, r0
					    dp4 r1.z, c2, v0
					    mov r3, r1
					    mov o2, r1
					    mov o1.xy, v1
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 20 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "VERTEXLIGHT_ON" "PIXELSNAP_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					div r1.xy, r0.xyxx, r0.wwww
					mul r1.zw, cb0[6].xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
					mul r1.xy, r1.zwzz, r1.xyxx
					round_ne r1.xy, r1.xyxx
					div r1.xy, r1.xyxx, r1.zwzz
					mul r0.xy, r0.wwww, r1.xyxx
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "VERTEXLIGHT_ON" "PIXELSNAP_ON" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _ScreenParams;
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//   _ScreenParams      c4       1
					//
					
					    vs_3_0
					    def c5, 0.5, 0, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r1.w, c3, v0
					    rcp r0.z, r1.w
					    mul r0.xy, r0.z, r0
					    mov r2.x, c5.x
					    mul r0.zw, r2.x, c4.xyxy
					    mad r0.xy, r0, r0.zwzw, c5.x
					    frc r2.xy, r0
					    add r0.xy, r0, -r2
					    rcp r2.x, r0.z
					    rcp r2.y, r0.w
					    mul r0.xy, r0, r2
					    mul r1.xy, r1.w, r0
					    dp4 r1.z, c2, v0
					    mov r3, r1
					    mov o2, r1
					    mov o1.xy, v1
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 20 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "VERTEXLIGHT_ON" "PIXELSNAP_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					div r1.xy, r0.xyxx, r0.wwww
					mul r1.zw, cb0[6].xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
					mul r1.xy, r1.zwzz, r1.xyxx
					round_ne r1.xy, r1.xyxx
					div r1.xy, r1.xyxx, r1.zwzz
					mul r0.xy, r0.wwww, r1.xyxx
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _GrabTexture;
					//   sampler2D _MainTex;
					//   float4 _MainTex_ST;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//   float _xOffset;
					//   float _yOffset;
					//
					//
					// Registers:
					//
					//   Name              Reg   Size
					//   ----------------- ----- ----
					//   _ProjectionParams c0       1
					//   _ScreenParams     c1       1
					//   _MainTex_ST       c2       1
					//   _xOffset          c3       1
					//   _yOffset          c4       1
					//   _GrabTexture      s0       1
					//   _MainTex          s1       1
					//
					
					    ps_3_0
					    def c5, 0.5, 1, 0, 0
					    dcl_texcoord v0.xy
					    dcl_texcoord1 v1.xyw
					    dcl_2d s0
					    dcl_2d s1
					    mul r0.x, c0.x, -c0.x
					    rcp r0.y, v1.w
					    mul r1.xy, r0.y, v1
					    mul r1.z, r0.x, r1.y
					    mad r0.xy, r1.xzzw, c5.x, c5.x
					    rcp r0.z, c1.x
					    mul r0.z, r0.z, c3.x
					    mad r1.xy, v0, c2, c2.zwzw
					    texld r1, r1, s1
					    mul r1.x, r0.z, r1.w
					    rcp r0.z, c1.y
					    mul r0.z, r0.z, c4.x
					    mul r1.y, r1.w, r0.z
					    add r0.xy, r0, r1
					    texld r0, r0, s0
					    mov oC0.xyz, r0
					    mov oC0.w, c5.y
					
					// approximately 17 instruction slots used (2 texture, 15 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xy w
					// SV_IsFrontFace           0   x           3    FFACE    uint       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.x, cb1[5].x, -cb1[5].x
					div r1.xy, v2.xyxx, v2.wwww
					mul r1.z, r0.x, r1.y
					mad r0.xy, r1.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
					mad r0.zw, v1.xxxy, cb0[2].xxxy, cb0[2].zzzw
					sample r1.xyzw, r0.zwzz, t1.xyzw, s1
					div r0.zw, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[6].xxxy
					mul r0.zw, r0.zzzw, cb0[3].xxxy
					mad r0.xy, r0.zwzz, r1.wwww, r0.xyxx
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _GrabTexture;
					//   sampler2D _MainTex;
					//   float4 _MainTex_ST;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//   float _xOffset;
					//   float _yOffset;
					//
					//
					// Registers:
					//
					//   Name              Reg   Size
					//   ----------------- ----- ----
					//   _ProjectionParams c0       1
					//   _ScreenParams     c1       1
					//   _MainTex_ST       c2       1
					//   _xOffset          c3       1
					//   _yOffset          c4       1
					//   _GrabTexture      s0       1
					//   _MainTex          s1       1
					//
					
					    ps_3_0
					    def c5, 0.5, 1, 0, 0
					    dcl_texcoord v0.xy
					    dcl_texcoord1 v1.xyw
					    dcl_2d s0
					    dcl_2d s1
					    mul r0.x, c0.x, -c0.x
					    rcp r0.y, v1.w
					    mul r1.xy, r0.y, v1
					    mul r1.z, r0.x, r1.y
					    mad r0.xy, r1.xzzw, c5.x, c5.x
					    rcp r0.z, c1.x
					    mul r0.z, r0.z, c3.x
					    mad r1.xy, v0, c2, c2.zwzw
					    texld r1, r1, s1
					    mul r1.x, r0.z, r1.w
					    rcp r0.z, c1.y
					    mul r0.z, r0.z, c4.x
					    mul r1.y, r1.w, r0.z
					    add r0.xy, r0, r1
					    texld r0, r0, s0
					    mov oC0.xyz, r0
					    mov oC0.w, c5.y
					
					// approximately 17 instruction slots used (2 texture, 15 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xy w
					// SV_IsFrontFace           0   x           3    FFACE    uint       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.x, cb1[5].x, -cb1[5].x
					div r1.xy, v2.xyxx, v2.wwww
					mul r1.z, r0.x, r1.y
					mad r0.xy, r1.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
					mad r0.zw, v1.xxxy, cb0[2].xxxy, cb0[2].zzzw
					sample r1.xyzw, r0.zwzz, t1.xyzw, s1
					div r0.zw, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[6].xxxy
					mul r0.zw, r0.zzzw, cb0[3].xxxy
					mad r0.xy, r0.zwzz, r1.wwww, r0.xyxx
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "PIXELSNAP_ON" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _GrabTexture;
					//   sampler2D _MainTex;
					//   float4 _MainTex_ST;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//   float _xOffset;
					//   float _yOffset;
					//
					//
					// Registers:
					//
					//   Name              Reg   Size
					//   ----------------- ----- ----
					//   _ProjectionParams c0       1
					//   _ScreenParams     c1       1
					//   _MainTex_ST       c2       1
					//   _xOffset          c3       1
					//   _yOffset          c4       1
					//   _GrabTexture      s0       1
					//   _MainTex          s1       1
					//
					
					    ps_3_0
					    def c5, 0.5, 1, 0, 0
					    dcl_texcoord v0.xy
					    dcl_texcoord1 v1.xyw
					    dcl_2d s0
					    dcl_2d s1
					    mul r0.x, c0.x, -c0.x
					    rcp r0.y, v1.w
					    mul r1.xy, r0.y, v1
					    mul r1.z, r0.x, r1.y
					    mad r0.xy, r1.xzzw, c5.x, c5.x
					    rcp r0.z, c1.x
					    mul r0.z, r0.z, c3.x
					    mad r1.xy, v0, c2, c2.zwzw
					    texld r1, r1, s1
					    mul r1.x, r0.z, r1.w
					    rcp r0.z, c1.y
					    mul r0.z, r0.z, c4.x
					    mul r1.y, r1.w, r0.z
					    add r0.xy, r0, r1
					    texld r0, r0, s0
					    mov oC0.xyz, r0
					    mov oC0.w, c5.y
					
					// approximately 17 instruction slots used (2 texture, 15 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "PIXELSNAP_ON" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xy w
					// SV_IsFrontFace           0   x           3    FFACE    uint       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.x, cb1[5].x, -cb1[5].x
					div r1.xy, v2.xyxx, v2.wwww
					mul r1.z, r0.x, r1.y
					mad r0.xy, r1.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
					mad r0.zw, v1.xxxy, cb0[2].xxxy, cb0[2].zzzw
					sample r1.xyzw, r0.zwzz, t1.xyzw, s1
					div r0.zw, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[6].xxxy
					mul r0.zw, r0.zzzw, cb0[3].xxxy
					mad r0.xy, r0.zwzz, r1.wwww, r0.xyxx
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "PIXELSNAP_ON" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _GrabTexture;
					//   sampler2D _MainTex;
					//   float4 _MainTex_ST;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//   float _xOffset;
					//   float _yOffset;
					//
					//
					// Registers:
					//
					//   Name              Reg   Size
					//   ----------------- ----- ----
					//   _ProjectionParams c0       1
					//   _ScreenParams     c1       1
					//   _MainTex_ST       c2       1
					//   _xOffset          c3       1
					//   _yOffset          c4       1
					//   _GrabTexture      s0       1
					//   _MainTex          s1       1
					//
					
					    ps_3_0
					    def c5, 0.5, 1, 0, 0
					    dcl_texcoord v0.xy
					    dcl_texcoord1 v1.xyw
					    dcl_2d s0
					    dcl_2d s1
					    mul r0.x, c0.x, -c0.x
					    rcp r0.y, v1.w
					    mul r1.xy, r0.y, v1
					    mul r1.z, r0.x, r1.y
					    mad r0.xy, r1.xzzw, c5.x, c5.x
					    rcp r0.z, c1.x
					    mul r0.z, r0.z, c3.x
					    mad r1.xy, v0, c2, c2.zwzw
					    texld r1, r1, s1
					    mul r1.x, r0.z, r1.w
					    rcp r0.z, c1.y
					    mul r0.z, r0.z, c4.x
					    mul r1.y, r1.w, r0.z
					    add r0.xy, r0, r1
					    texld r0, r0, s0
					    mov oC0.xyz, r0
					    mov oC0.w, c5.y
					
					// approximately 17 instruction slots used (2 texture, 15 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "PIXELSNAP_ON" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xy w
					// SV_IsFrontFace           0   x           3    FFACE    uint       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.x, cb1[5].x, -cb1[5].x
					div r1.xy, v2.xyxx, v2.wwww
					mul r1.z, r0.x, r1.y
					mad r0.xy, r1.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
					mad r0.zw, v1.xxxy, cb0[2].xxxy, cb0[2].zzzw
					sample r1.xyzw, r0.zwzz, t1.xyzw, s1
					div r0.zw, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[6].xxxy
					mul r0.zw, r0.zzzw, cb0[3].xxxy
					mad r0.xy, r0.zwzz, r1.wwww, r0.xyxx
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	Fallback "Diffuse"
	CustomEditor "ShaderForgeMaterialInspector"
}