Shader "Shader Forge/Shimmer" {
	Properties {
		_Noise1 ("Noise1", 2D) = "bump" {}
		_xSpeed ("xSpeed", Float) = 1
		_ySpeed ("ySpeed", Float) = 1
		_xAmount ("xAmount", Float) = 0
		_yAmount ("yAmount", Float) = 0
	}
	SubShader {
		Tags { "CanUseSpriteAtlas" = "true" "DisableBatching" = "true" "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent" "RenderType" = "Opaque" }
		GrabPass {
			"Refraction"
		}
		Pass {
			Name "FORWARD"
			Tags { "CanUseSpriteAtlas" = "true" "DisableBatching" = "true" "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "ForwardBase" "PreviewType" = "Plane" "QUEUE" = "Transparent" "RenderType" = "Opaque" "SHADOWSUPPORT" = "true" }
			ZClip Off
			ZWrite Off
			Cull Off
			GpuProgramID 49720
			Program "vp" {
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov r1, r0
					    mov o2, r0
					    mov o1.xy, v1
					    mad o0.xy, r1.w, c255, r1
					    mov o0.zw, r1
					
					// approximately 9 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov r1, r0
					    mov o2, r0
					    mov o1.xy, v1
					    mad o0.xy, r1.w, c255, r1
					    mov o0.zw, r1
					
					// approximately 9 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "VERTEXLIGHT_ON" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov r1, r0
					    mov o2, r0
					    mov o1.xy, v1
					    mad o0.xy, r1.w, c255, r1
					    mov o0.zw, r1
					
					// approximately 9 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "VERTEXLIGHT_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "VERTEXLIGHT_ON" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov r1, r0
					    mov o2, r0
					    mov o1.xy, v1
					    mad o0.xy, r1.w, c255, r1
					    mov o0.zw, r1
					
					// approximately 9 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "VERTEXLIGHT_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D Refraction;
					//   sampler2D _Noise1;
					//   float4 _Noise1_ST;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//   float4 _Time;
					//   float4 _TimeEditor;
					//   float _xAmount;
					//   float _xSpeed;
					//   float _yAmount;
					//   float _ySpeed;
					//
					//
					// Registers:
					//
					//   Name              Reg   Size
					//   ----------------- ----- ----
					//   _Time             c0       1
					//   _ProjectionParams c1       1
					//   _ScreenParams     c2       1
					//   _TimeEditor       c3       1
					//   _Noise1_ST        c4       1
					//   _ySpeed           c5       1
					//   _xSpeed           c6       1
					//   _xAmount          c7       1
					//   _yAmount          c8       1
					//   Refraction        s0       1
					//   _Noise1           s1       1
					//
					
					    ps_3_0
					    def c9, 0.5, 2, -1, 1
					    dcl_texcoord v0.xy
					    dcl_texcoord1 v1.xyw
					    dcl_2d s0
					    dcl_2d s1
					    mul r0.x, c1.x, -c1.x
					    rcp r0.y, v1.w
					    mul r1.xy, r0.y, v1
					    mul r1.z, r0.x, r1.y
					    mad r0.xy, r1.xzzw, c9.x, c9.x
					    mov r1.x, c0.x
					    add r0.z, r1.x, c3.x
					    mul r1.x, r0.z, c6.x
					    mul r1.y, r0.z, c5.x
					    add r0.zw, r1.xyxy, v0.xyxy
					    mad r0.zw, r0, c4.xyxy, c4
					    texld_pp r1, r0.zwzw, s1
					    mad_pp r0.zw, r1.xywy, c9.y, c9.z
					    rcp r1.x, c2.x
					    mul r0.z, r0.z, r1.x
					    mul r1.x, r0.z, c7.x
					    rcp r0.z, c2.y
					    mul r0.z, r0.z, r0.w
					    mul r1.y, r0.z, c8.x
					    add r0.xy, r0, r1
					    texld r0, r0, s0
					    mov oC0.xyz, r0
					    mov oC0.w, c9.w
					
					// approximately 23 instruction slots used (2 texture, 21 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xy w
					// SV_IsFrontFace           0   x           3    FFACE    uint       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					add r0.x, cb0[2].x, cb1[0].x
					mad r0.xy, r0.xxxx, cb0[4].yxyy, v1.xyxx
					mad r0.xy, r0.xyxx, cb0[3].xyxx, cb0[3].zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s1
					mad r0.xy, r0.wyww, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					div r0.zw, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[6].xxxy
					mul r0.xy, r0.xyxx, r0.zwzz
					mul r0.z, cb1[5].x, -cb1[5].x
					div r1.xy, v2.xyxx, v2.wwww
					mul r1.z, r0.z, r1.y
					mad r0.zw, r1.xxxz, l(0.000000, 0.000000, 0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
					mad r0.xy, cb0[4].zwzz, r0.xyxx, r0.zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D Refraction;
					//   sampler2D _Noise1;
					//   float4 _Noise1_ST;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//   float4 _Time;
					//   float4 _TimeEditor;
					//   float _xAmount;
					//   float _xSpeed;
					//   float _yAmount;
					//   float _ySpeed;
					//
					//
					// Registers:
					//
					//   Name              Reg   Size
					//   ----------------- ----- ----
					//   _Time             c0       1
					//   _ProjectionParams c1       1
					//   _ScreenParams     c2       1
					//   _TimeEditor       c3       1
					//   _Noise1_ST        c4       1
					//   _ySpeed           c5       1
					//   _xSpeed           c6       1
					//   _xAmount          c7       1
					//   _yAmount          c8       1
					//   Refraction        s0       1
					//   _Noise1           s1       1
					//
					
					    ps_3_0
					    def c9, 0.5, 2, -1, 1
					    dcl_texcoord v0.xy
					    dcl_texcoord1 v1.xyw
					    dcl_2d s0
					    dcl_2d s1
					    mul r0.x, c1.x, -c1.x
					    rcp r0.y, v1.w
					    mul r1.xy, r0.y, v1
					    mul r1.z, r0.x, r1.y
					    mad r0.xy, r1.xzzw, c9.x, c9.x
					    mov r1.x, c0.x
					    add r0.z, r1.x, c3.x
					    mul r1.x, r0.z, c6.x
					    mul r1.y, r0.z, c5.x
					    add r0.zw, r1.xyxy, v0.xyxy
					    mad r0.zw, r0, c4.xyxy, c4
					    texld_pp r1, r0.zwzw, s1
					    mad_pp r0.zw, r1.xywy, c9.y, c9.z
					    rcp r1.x, c2.x
					    mul r0.z, r0.z, r1.x
					    mul r1.x, r0.z, c7.x
					    rcp r0.z, c2.y
					    mul r0.z, r0.z, r0.w
					    mul r1.y, r0.z, c8.x
					    add r0.xy, r0, r1
					    texld r0, r0, s0
					    mov oC0.xyz, r0
					    mov oC0.w, c9.w
					
					// approximately 23 instruction slots used (2 texture, 21 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xy w
					// SV_IsFrontFace           0   x           3    FFACE    uint       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					add r0.x, cb0[2].x, cb1[0].x
					mad r0.xy, r0.xxxx, cb0[4].yxyy, v1.xyxx
					mad r0.xy, r0.xyxx, cb0[3].xyxx, cb0[3].zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s1
					mad r0.xy, r0.wyww, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					div r0.zw, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[6].xxxy
					mul r0.xy, r0.xyxx, r0.zwzz
					mul r0.z, cb1[5].x, -cb1[5].x
					div r1.xy, v2.xyxx, v2.wwww
					mul r1.z, r0.z, r1.y
					mad r0.zw, r1.xxxz, l(0.000000, 0.000000, 0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
					mad r0.xy, cb0[4].zwzz, r0.xyxx, r0.zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	Fallback "Diffuse"
	CustomEditor "ShaderForgeMaterialInspector"
}